[package]
name = "chokidar"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
notify-debouncer-full = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.38", features = ["process", "event"] }

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
